# Generated by Django 4.1.7 on 2023-03-03 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='webapp.type', verbose_name='Тип задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='webapp.status', verbose_name='Статус'),
        ),
    ]
