# Generated by Django 4.1.7 on 2023-03-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_status_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='webapp.type', verbose_name='Тип задачи'),
        ),
    ]
