# Generated by Django 4.1.7 on 2023-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_task_type_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Cтатус'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='types', to='webapp.type', verbose_name='Тип задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ManyToManyField(related_name='tasks', to='webapp.status', verbose_name='Статус'),
        ),
    ]
